apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.name }}-secret"
  labels:
    app: "{{ .Values.app.label }}-label"
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
{{- range .Values.envs }}
  {{ .name }}: {{ .value | b64enc | quote }}
{{- end }}
  