apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  namespace: {{ .Values.app.namespace }}
  labels:
    app: "{{ .Values.app.label }}-label"
spec:
  selector:
    app: "{{ .Values.app.label }}-label"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
  type: {{ .Values.service.type }}