apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  namespace: {{ .Values.app.namespace }}
  
spec:
  selector:
    app: "{{ .Values.app.label }}-label"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.port }}
  type: LoadBalancer