# Application configuration
app:
  name: portfolio
  label: portfolio
  namespace: portfolio

# Replica count for the deployment
replicaCount: 2
service: 
  type: ClusterIP
# Image configuration
image:
  name: portfolio-backend
  repository: docker.io/natngoc/portfolito
  tag: "1.0"
  port: 3002

# Environment variables
envs:
  - name: TYPE_DB
    value: "postgres"  
  - name: HOST_DB
    value: "example-key" 
  - name: PORT_DB
    value: "5432" 
  - name: USER_DB
    value: "postgres"  
  - name: PASS_DB
    value: "admin"  
  - name: NAME_DB
    value: "postgres"  
  - name: PORT
    value: "3002"
  - name: JWT_SECRET
    value: "nguyenanhtuanngoc"  
  - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
    value: "1h"
  - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
    value: "7d"

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
